static/css/base.css, static/js/query_form.js, templates/core/index.html
Resolves #9.
(Sorry for the messy diff; I forgot I had my formatter turned on!)
Adds a nice CSS tooltip to the data categories and removes the changing text to the right of the buttons.
See https://blog.logrocket.com/creating-beautiful-tooltips-with-only-css/ for implementation details! The short version is I used a custom `data-text` attribute to define the tooltip content, and created a `.with-tooltip` class which gives us an easy way to put tooltips on whatever we want.
I also:
- Rounded the category buttons because everybody loves rounded rectangles and it matches our other buttons
- Change the cursor for the category buttons and our other buttons to `pointer` since that's the standard signifier for clickable elements
PS. This is a solid iteration over what we have, but as we think …
=> Replace category helptext with a nice tooltip

static/css/base.css, static/js/query_form.js, templates/core/index.html
Resolves #14.
Disables the Find Articles button until a data type has been selected, then uses it form validation until a source has been selected.
(I'm not sure if destination is supposed to be required or not @lisad? For what it's worth, it apparently doesn't _need_ to be selected [see recording below]. If it's supposed to be required, I can update this to make it)
[Screencast from 2024-02-20 15-46-07.webm](https://github.com/dtinit/portmap/assets/6510436/bacba13e-7373-45e3-9318-47cd6c272711)
=> Disable Find Articles button until a source is selected

static/css/base.css
Resolves #26.
Relates to #23.
Just unnests some CSS rules since the support isn't quite good enough yet. I also dropped a rule that applied to `:where(a)` since it wasn't doing anything (there's another rule matching just `a` which will always take precedence over `:where(a)`)
=> Unnest CSS rules

.eslintrc.json, .github/workflows/lint-js.yml, README.md, package-lock.json, package.json, static/js/article.js, static/js/query_form.js
Closes #31.
Relates to #23. ESLint should tell us if we try to use features from ES7+.
Relates to #39.
- Adds a package.json file to support npm dependencies
- Adds ESLint as a dev dependency from npm
- Adds an ESLint configuration file with just the basic recommended rules for now. It applies to all JavaScript files in `static/js` except for minified ones like `html.min.js`.
- Adds an npm script so we can run the linter with `npm run lint`
- Adds a GitHub Action to run ESLint for pull requests to the main branch
- Adds linting instructions to README.md
- Fixes a few bad practices ESLint already caught (missing variable declarations)
For now I'm just informing ESLint about global variables like `lucide` and `queryStructure` at the top of the files that use them.
=> Setup ESLint

portmap/core/views.py, templates/core/index.html
Resolves #21.
Resolves #22.
Changes the /find_articles view to accept a GET instead of a POST, and updates the index page to send a GET request instead. This automagically puts the query params in the URL (#22) which can then be shared to view the same page. The query params are still sent to the server and logged.
=> Use a GET request for /find_articles instead of a POST

portmap/core/views.py, templates/core/article_list.html, templates/core/index.html
Closes #40.
Creates a list of all articles when `/find_articles` isn't provided a datatype:
Also adds a link to it from the home page (below "Find Article"):
As the number of articles grows, we'll need to build on this (grouping articles by category, etc), but I think this is the perfect first step to make the articles crawlable.
=> Add article index page and provide path for search engines to crawl it

portmap/core/views.py, portmap/urls.py, static/css/base.css, templates/core/about.html, templates/core/article.html, templates/core/article_list.html, templates/core/index.html, templates/core/thankyou.html, templates/includes/nav-bar.html
Closes #47 (I took some creative liberties!)
- Adds an "About" page with the information from #47.
- Adds a top nav where the most important pages can be accessed from every page. This nav matches the one on dtinit.org
=> Add "About" page and a nav bar

portmap/core/forms.py, static/css/base.css, static/js/article.js, templates/forms/widgets/unwrapped_radio_option.html
Closes #34.
Closes #36.
Visual improvements to the article feedback buttons. Also makes sure the explanation field reveals for both positive and negative feedback.
Before:
After:
=> Article feedback UI/UX improvements

static/css/base.css, static/js/query_form.js, templates/core/index.html
Closes #35.
Makes it easier to see that you can click on "Can't find what you're looking for?" Also removes the button on click, so the form effectively replaces it rather than be appended below it.
**Before**
**After**
=> Improve signifier for index feedback form reveal

portmap/core/views.py, static/css/base.css, static/js/query_form.js, templates/core/index.html
Closes #60.
- Removes the faux document style to make the design cleaner and free up the total padding and margins around the document (especially on mobile)
- Also moves the header/nav up to the top of the page
- Changes the datatype selection radios to be bigger and include the help text, removing the need for tooltips which are always awkward with touch inputs
- Also removes the "[[DATATYPE]]: ..." label from the help text which was a bit redundant
- Styles the selects to match other elements
- Removes the striping on the article list table
I'm open to feedback & suggestions of course! (@Gogo-ug1?)
=> Design updates

portmap/core/views.py
Closes #82.
Sets `cache-control` to `public` with a maximum age of 24 hours for the index page and about page. I skipped the article pages because the caching could interfere with view tracking.
=> Enable better cache support for index page with `cache-control` headers

portmap/core/admin.py, portmap/core/models.py
The main function of this PR is to add the TrackArticleView model to Django Admin View and in this way be able to verify which articles were visited and how the user reached them.
Each visit to an article increments the corresponding count field displayed in the Admin View.
I'm currently working on a better way to filter.
=> Adding TrackArticleView to Admin View

.github/workflows/django.yml
Related to #78.
Updates the workflow file to be trigger-able with [`repository_dispatch`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch), so we can trigger it from the portability-articles repo when content changes.
We don't actually need to do a full redeploy when portability-articles changes; we just need to repopulate the articles and regenerate index.html (`manage.py refresh`) on the live instance, which is the approach I started with for this ticket. However, that was turning out to be much more work than just redeploying, and I don't see any harm in just doing a full deployment every time.
=> Update deployment workflow to be dispatchable from outside the repository

portmap/core/views.py, requirements.txt
Closes #94.
Changes our Markdown library to more closely match GitHub, so articles will look the same in GitHub and on Portmap.
**Fixed list:**
I glanced through every article and didn't see any obvious issues.
=> Switch to pycmarkgfm for converting markdown to HTML

.github/workflows/django.yml
Fixes #95.
- Bumps [actions/checkout](https://github.com/actions/checkout) to v4
- Bumps [actions/setup-python](https://github.com/actions/setup-python) to v5
- Bumps [actions/setup-node](https://github.com/actions/setup-node) to v4
Even though these are major version bumps, it looks like we don't need to change anything else to use them.
=> Bump GitHub action versions

docs/reference/static-pages.md
Closes #92.
Adds documentation for the static home page introduced in #86.
=> Document static page process

portmap/core/views.py, static/css/base.css, templates/core/thankyou.html
Closes #88.
Minor updates to the thank you page (for feedback). Also adds a "back" link to return the user to the previous page.
=> Redo thank you page

portmap/core/admin.py, portmap/core/views.py, portmap/urls.py, requirements.txt, templates/core/article_list.html
- URL to access RSS Feed changed from https://portmap.dtinit.org/articles_feed/ to simply https://portmap.dtinit.org/rss/
- There is a button now in https://portmap.dtinit.org/find_articles that will redirect the user to the RSS Feed.
- `created_at` field was added as suggested.
- HTML is now being display instead of markdown in the RSS Feed. This should allow us to display it as expected when reading it on a RSS reader such as Feedly.
- Lastly, we can now sort the View Count field in the Article Admin View.
Still working in a way to allow sort by `created_at` in the RSS Feed.
Closes #100 and Closes #97
=> Rss feed updates

portmap/core/admin.py, static/css/admin/analytics.css, static/js/admin/analytics.js, templates/admin/analytics.html
Sorta kinda closes #102.
I wasn't able to find a way to use Streamlit without setting up a Streamlit server (see https://github.com/dtinit/portmap/issues/102#issuecomment-2135880526), and I felt this would really complicate our setup just to add some exploratory charts. Instead, I created a few charts using a regular ol' Django view and JavaScript.
The view is accessible at `/dj-admin/analytics` (TODO: add a link from the admin portal?) and requires "staff member" permissions to view (super admin works too).
:rotating_light: **These screenshots show data from my local db; not production!** :rotating_light:
=> Add analytics for admins

portmap/core/articles.py, tests/core/test_gh_articles.py
In running the inner error (with YAML parsing) was getting swallowed by the outer one (reporting a Github API issue)
With this reorganization, the errors are no longer nested, and also the article parsing section is easier to test standalone, we don't even have to mock out github client
This fixes #114
=> Re-organizes the get articles code so that errors aren't nested

portmap/core/views.py
Closes #119.
Stops sending Slack notifications every time someone queries for articles.
=> Remove slack notification for queries

tests/e2e/playwright_test_suite.py, tests/e2e/test_article.py, tests/e2e/test_find_articles.py, tests/e2e/test_index.py
Closes #131.
- Creates a class `PlaywrightTestSuite` to handle things like Playwright set up, but also client-side error collection and reporting
- Any test which generates uncaught client-side errors will fail, and the errors will be reported to the console:
- I added `headless=True` in the call to `launch()` and left a comment explaining you can change it to `False` to launch Chromium with its GUI so you can actually watch the tests execute
- I updated our test suites to subclass this
The diff looks bigger than it is. All I did within the actual tests is remove `page = self.context.new_page()` and replace all other instances of `page` with `self.page`.
=> Improve E2E debug experience

portmap/core/admin.py, templates/admin/analytics.html
The lengths I go to, so as not to write javascript!  ;)
=> Adding the dumbest possible visualization of happy/sad article reactions

portmap/core/articles.py
Quick PR to avoid having articles with duplicate names we can ensure that `get_content_files` checks for duplicates before calling `process_article`.
- A set `seen_articles` is used to keep track of article names that have already been processed.
- Before processing each article, the code checks if the article name is already in the `seen_articles` set.
- If the article name is already in the set, the article is skipped.
- If the article name is not in the set, it is added to the set, and the article is processed and added to the `article_data` dictionary.
With this approach in `get_content_files`, we avoid processing duplicate articles from the GitHub API response. However, it does not skip articles that already exist in the database, ensuring that updates to articles are processed. …
=> Dismiss duplicate articles

portmap/core/views.py, requirements.txt
If we want to ensure that URLs are not clickable when displayed in Slack, Django Admin or other contexts, we can use the `bleach` library to sanitize the text and remove any potential clickable URLs.
The `bleach.clean` function can be configured to remove all tags and attributes and will ensure that URLs are not clickable.
1. **User Submits Feedback**:
- Reaction: "Positive"
- Explanation: "Check out this link: http://example.com/"
2. **Form Validation**:
- form.is_valid() returns `True` because the data is valid.
3. **Sanitization**:
- `bleach.clean(form.cleaned_data['explanation'], tags=[], attributes={}, strip=True)` removes any HTML tags and ensures that the URL remains as plain text.
- The sanitized explanation becomes: "Check out this link: http://example.com/"
4. **Save to …
=> Sanitize html clickable links feedback

portmap/core/views.py
We were using dictionary-style access with square brackets: `form.data['datasource']`. This fails if someone hits the endpoint without providing all expected parameters.
In this updated code instead of using form.data['datasource'], we use `form.data.get('datasource', '')`
The .get() method:
- Returns the value if the key exists
- Returns the default value (empty string in our case) if the key doesn't exist
- Never raises a KeyError/MultiValueDictKeyError
`datasource` and `datadest` were also modified.
Closes #113
=> Fixing Server Error - MultiValueDictKeyError

portmap/core/admin.py
The analytics page was crashing in production due to memory overflow when processing large amounts of data.  Server was running out of memory trying to load everything at once, causing 500 errors in production when accessing the analytics page. 
This PR fixes that by optimizing how we handle data processing. It restructured how we fetch and process data to be more memory-efficient while keeping the exact same functionality and output. 
- Process QueryLogs in chunks using iterator() instead of loading everything at once
- Let the database handle counting (instead of Python doing it)
- Only fetch the fields we actually need for sentiment analysis
- Clean up dictionary operations for better memory usage
Closes #146
=> fix(analytics): Optimize memory usage in analytics view
